version: 2
updates:
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: /hardware-testing/unifi-os-server/docker-compose
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
