name: CI - HIL

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    name: Main
    runs-on:
      - self-hosted
      - terrifi-hardware-test
    env:
      UNIFI_API: https://192.168.1.3:11443
      UNIFI_API_KEY: ${{ secrets.TERRIFI_HIL_TEST_UNIFI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Taskfile
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Check UniFi API key
        run: task checkAPIKey
      - name: Download Go dependencies
        run: task deps
      - name: Build
        run: task build
      # - name: Acceptance tests (HIL)
      #   run: task test:acc:hardware
